# Site settings
title: Monochrome | A minimal, responsive Jekyll blog theme
description: "A minimal, responsive, ready to use blog template, built with Jekyll."
url: "http://www.dyutibarma.github.io/monochrome"
author:
  name: "The Review Index"
  email: "dyutibarma@gmail.com"
  url: "https://thereviewindex.com"

# Build settings
baseurl: /monochrome # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/
title: "Florian Mattana"
description: "From naive GEMM to Flash Attention â€” implementing and profiling GPU kernels in CUDA, documented step by step."
url: "https://florianmattana.com"

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
